const noodlesData = [
    {
        name: 'Ветчина & гриб',
        composition: ['cливочный соус', 'чеддер', 'пармезан', 'моцарелла', 'горгонзола'],
        price: [500],
        height:"23vw",
        width:"23vw", 
        left:"67vw", 
        top:"7vw", 
        animationDelay:"1.5s",
        backgroundImage:"url(/art/salad2.jpg)",
        rotateOffset: '100deg',
        itemType:'interactive',
        rotationDirection: 'reverse',
        infoImage:"url(/art/ham-mushrooms.svg)",
        infoTop:"5vw",
        infoLeft:"-21vw",
    },

    {
        name: 'Арабьята',
        composition: ['cливочный соус', 'чеддер', 'пармезан', 'моцарелла', 'горгонзола'],
        price: [500],
        height:"23vw", 
        width:"23vw", 
        left:"31.8vw", 
        top:"27.5vw", 
        animationDelay:"0.5s",
        backgroundImage:"url(/art/salad2.jpg)",
        rotateOffset: '180deg',
        itemType:'interactive',
        rotationDirection: 'normal',
        infoImage:"url(/art/arabyata.svg)",
        infoTop:"23vw",
        infoLeft:"2vw",
    },

    {
        name: 'Паста с лососем',
        composition: ['cливочный соус', 'чеддер', 'пармезан', 'моцарелла', 'горгонзола'],
        price: [500],
        height:"19vw", 
        width:"19vw", 
        left:"69vw", 
        top:"30vw", 
        animationDelay:"2.3s",
        backgroundImage:"url(/art/salad2.jpg)",
        rotateOffset: '10deg',
        itemType:'interactive',
        rotationDirection: 'normal',
        infoImage:"url(/art/ham-mushrooms.svg)",
        infoTop:"5vw",
        infoLeft:"-18vw",

    },

    {
        name: 'лапша4',
        composition: ['cливочный соус', 'чеддер', 'пармезан', 'моцарелла', 'горгонзола'],
        price: [500],
        height:"18vw", 
        width:"18vw", 
        left:"53vw", 
        top:"21.5vw", 
        animationDelay:"0.85s",
        backgroundImage:"url(/art/salad2.jpg)",
        rotateOffset: '200deg',
        itemType:'decoractive',
        rotationDirection: 'normal',
        infoImage:"url(/art/ham-mushrooms.svg)",
        infoTop:"5vw",
        infoLeft:"-18vw",

    },

    {
        name: 'А-ля норма',
        composition: ['cливочный соус', 'чеддер', 'пармезан', 'моцарелла', 'горгонзола'],
        price: [500],
        height:"18vw", 
        width:"18vw", 
        left:"16vw", 
        top:"21vw", 
        animationDelay:"1.9s",
        backgroundImage:"url(/art/salad2.jpg)",
        rotateOffset: '300deg',
        itemType:'interactive',
        rotationDirection: 'reverse',
        infoImage:"url(/art/alanorma.svg)",
        infoTop:"-4vw",
        infoLeft:"9vw",

    },

    {
        name: 'Карбонара',
        composition: ['cливочный соус', 'чеддер', 'пармезан', 'моцарелла', 'горгонзола'],
        price: [500],
        height:"18vw", 
        width:"18vw", 
        left:"16vw", 
        top:"39vw", 
        animationDelay:"5.2s",
        backgroundImage:"url(/art/salad4.jpg)",
        rotateOffset: '0deg',
        itemType:'interactive',
        rotationDirection: 'normal',
        infoImage:"url(/art/carbonara.svg)",
        infoTop:"0vw",
        infoLeft:"-11vw",
        
    },

    {
        name: 'hex1',
        height:"8vw", 
        width:"8vw", 
        left:"11vw", 
        top:"17.5vw", 
        animationDelay:"3.6s",
        backgroundColor:"#f0c000",
        itemType:'decoration',
        rotationDirection: 'reverse',
        infoImage:"url(/art/ham-mushrooms.svg)",
        infoTop:"5vw",
        infoLeft:"-18vw",
    },
    
    {
        name: 'hex2',
        height:"9vw", 
        width:"9vw", 
        left:"57.5vw", 
        top:"44vw",
        backgroundColor:"#ffc400",
        itemType:"decoration",
        rotationDirection: 'normal',
        infoImage:"url(/art/ham-mushrooms.svg)",
        infoTop:"5vw",
        infoLeft:"-18vw",

    },

    {
        name: 'hex3',
        height:"9vw", 
        width:"9vw", 
        left:"65.8vw", 
        top:"49vw",
        backgroundColor:"#ff9100",
        itemType:"decoration",
        rotationDirection: 'normal',
        infoImage:"url(/art/ham-mushrooms.svg)",
        infoTop:"5vw",
        infoLeft:"-18vw",
    }, 
]

export default noodlesData